### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by efyphil** [NVlabs/learningrigidity#3]
Hello, I want to comare my point cloud aligner with your, but I have some trouble with import pyflow2pose. gtsam and flow2pose was built without proublem
ImportError                               Traceback (most recent call last)
<ipython-input-2-20a2161638ab> in <module>
      1 sys.path.append('external_packages/flow2pose/build')
----> 2 from pyFlow2Pose import pyFlow2Pose

ImportError: external_packages/flow2pose/build/pyFlow2Pose.so: undefined symbol: _ZN5pbcvt16fromNDArrayToMatEP7_object

**Comment by efyphil** [comment]
![screenshot from 2019-01-22 10-41-06](https://user-images.githubusercontent.com/38631588/51519716-d9a24800-1e32-11e9-93b1-d039011f6ed8.png)
![screenshot from 2019-01-22 10-42-33](https://user-images.githubusercontent.com/38631588/51519757-f2aaf900-1e32-11e9-8e9f-739f18a13f07.png)
maybe I have some problem with gtsam?
I think built and linked was correct

**Comment by lvzhaoyang** [comment]
The interface function looks like a opencv function which did not get linked correctly. 

I went through your cmake config output. Actually, I have never used opencv4 before (at least I did not test it with this repo). I think I was using the system default 2.4.11 on Ubuntu 16.04. Maybe that could be the reason?

**Comment by efyphil** [comment]
Yes, I think so, I try to use different opencv thanks a lot
